// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cockroachdb/cockroach/pkg/cmd/tef/planners (interfaces: Planner)

// Package demo is a generated GoMock package.
package demo

import (
	context "context"
	reflect "reflect"

	planners "github.com/cockroachdb/cockroach/pkg/cmd/tef/planners"
	"github.com/golang/mock/gomock"
)

// MockPlanner is a mock of Planner interface.
type MockPlanner struct {
	ctrl     *gomock.Controller
	recorder *MockPlannerMockRecorder
}

// MockPlannerMockRecorder is the mock recorder for MockPlanner.
type MockPlannerMockRecorder struct {
	mock *MockPlanner
}

// NewMockPlanner creates a new mock instance.
func NewMockPlanner(ctrl *gomock.Controller) *MockPlanner {
	mock := &MockPlanner{ctrl: ctrl}
	mock.recorder = &MockPlannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanner) EXPECT() *MockPlannerMockRecorder {
	return m.recorder
}

// NewCallbackTask mocks base method.
func (m *MockPlanner) NewCallbackTask(arg0 context.Context, arg1 string) *planners.CallbackTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCallbackTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.CallbackTask)
	return ret0
}

// NewCallbackTask indicates an expected call of NewCallbackTask.
func (mr *MockPlannerMockRecorder) NewCallbackTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCallbackTask", reflect.TypeOf((*MockPlanner)(nil).NewCallbackTask), arg0, arg1)
}

// NewChildPlanTask mocks base method.
func (m *MockPlanner) NewChildPlanTask(arg0 context.Context, arg1 string) *planners.ChildPlanTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChildPlanTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.ChildPlanTask)
	return ret0
}

// NewChildPlanTask indicates an expected call of NewChildPlanTask.
func (mr *MockPlannerMockRecorder) NewChildPlanTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChildPlanTask", reflect.TypeOf((*MockPlanner)(nil).NewChildPlanTask), arg0, arg1)
}

// NewConditionTask mocks base method.
func (m *MockPlanner) NewConditionTask(arg0 context.Context, arg1 string) *planners.ConditionTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConditionTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.ConditionTask)
	return ret0
}

// NewConditionTask indicates an expected call of NewConditionTask.
func (mr *MockPlannerMockRecorder) NewConditionTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConditionTask", reflect.TypeOf((*MockPlanner)(nil).NewConditionTask), arg0, arg1)
}

// NewEndTask mocks base method.
func (m *MockPlanner) NewEndTask(arg0 context.Context, arg1 string) *planners.EndTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEndTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.EndTask)
	return ret0
}

// NewEndTask indicates an expected call of NewEndTask.
func (mr *MockPlannerMockRecorder) NewEndTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEndTask", reflect.TypeOf((*MockPlanner)(nil).NewEndTask), arg0, arg1)
}

// NewExecutionTask mocks base method.
func (m *MockPlanner) NewExecutionTask(arg0 context.Context, arg1 string) *planners.ExecutionTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewExecutionTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.ExecutionTask)
	return ret0
}

// NewExecutionTask indicates an expected call of NewExecutionTask.
func (mr *MockPlannerMockRecorder) NewExecutionTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewExecutionTask", reflect.TypeOf((*MockPlanner)(nil).NewExecutionTask), arg0, arg1)
}

// NewForkJoinTask mocks base method.
func (m *MockPlanner) NewForkJoinTask(arg0 context.Context, arg1 string) *planners.ForkJoinTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewForkJoinTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.ForkJoinTask)
	return ret0
}

// NewForkJoinTask indicates an expected call of NewForkJoinTask.
func (mr *MockPlannerMockRecorder) NewForkJoinTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewForkJoinTask", reflect.TypeOf((*MockPlanner)(nil).NewForkJoinTask), arg0, arg1)
}

// NewForkTask mocks base method.
func (m *MockPlanner) NewForkTask(arg0 context.Context, arg1 string) *planners.ForkTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewForkTask", arg0, arg1)
	ret0, _ := ret[0].(*planners.ForkTask)
	return ret0
}

// NewForkTask indicates an expected call of NewForkTask.
func (mr *MockPlannerMockRecorder) NewForkTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewForkTask", reflect.TypeOf((*MockPlanner)(nil).NewForkTask), arg0, arg1)
}

// RegisterExecutor mocks base method.
func (m *MockPlanner) RegisterExecutor(arg0 context.Context, arg1 *planners.Executor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterExecutor", arg0, arg1)
}

// RegisterExecutor indicates an expected call of RegisterExecutor.
func (mr *MockPlannerMockRecorder) RegisterExecutor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterExecutor", reflect.TypeOf((*MockPlanner)(nil).RegisterExecutor), arg0, arg1)
}

// RegisterPlan mocks base method.
func (m *MockPlanner) RegisterPlan(arg0 context.Context, arg1, arg2 planners.Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterPlan", arg0, arg1, arg2)
}

// RegisterPlan indicates an expected call of RegisterPlan.
func (mr *MockPlannerMockRecorder) RegisterPlan(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPlan", reflect.TypeOf((*MockPlanner)(nil).RegisterPlan), arg0, arg1, arg2)
}
