-------Begin Transaction------
BEGIN;
UPDATE customer SET (c_balance, c_ytd_payment, c_payment_cnt, c_data) = (":-:|'c_balance','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','customer'|:-:", ":-:|'c_ytd_payment','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','customer'|:-:", ":-:|'c_payment_cnt','INT8','NOT NULL','','','','','','UPDATE','customer'|:-:", ":-:|'c_data','VARCHAR(500)','NOT NULL','','','','','','UPDATE','customer'|:-:") WHERE ((c_w_id = ":-:|'c_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:") AND (c_d_id = ":-:|'c_d_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:")) AND (c_id = ":-:|'c_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:") RETURNING c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_since, c_credit, c_credit_lim, c_discount, c_balance, CASE c_credit WHEN ":-:|'c_credit','CHAR(2)','NOT NULL','','','','','','INSERT','customer'|:-:" THEN left(c_data, _) ELSE ":-:|'c_credit','CHAR(2)','NOT NULL','','','','','','INSERT','customer'|:-:" END;
INSERT INTO history(h_c_id, h_c_d_id, h_c_w_id, h_d_id, h_w_id, h_amount, h_date, h_data) VALUES (":-:|'h_c_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_c_d_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_c_w_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_d_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','INSERT','history'|:-:", ":-:|'h_amount','DECIMAL(6,2)','NULL','','','','','','INSERT','history'|:-:", ":-:|'h_date','TIMESTAMP','NULL','','','','','','INSERT','history'|:-:", ":-:|'h_data','VARCHAR(24)','NULL','','','','','','INSERT','history'|:-:");
UPDATE warehouse SET w_ytd = w_ytd + ":-:|'w_ytd','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','warehouse'|:-:" WHERE w_id = ":-:|'w_id','INT8','NOT NULL','PRIMARY KEY','','UNIQUE','','','WHERE','warehouse'|:-:" RETURNING w_name, w_street_1, w_street_2, w_city, w_state, w_zip;
SELECT c_id FROM customer WHERE ((c_w_id = ":-:|'c_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:") AND (c_d_id = ":-:|'c_d_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:")) AND (c_last = ":-:|'c_last','VARCHAR(16)','NOT NULL','','','','','','WHERE','customer'|:-:") ORDER BY c_first ASC;
SELECT c_id FROM customer WHERE ((c_w_id = ":-:|'c_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:") AND (c_d_id = ":-:|'c_d_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:")) AND (c_last = ":-:|'c_last','VARCHAR(16)','NOT NULL','','','','','','WHERE','customer'|:-:") ORDER BY c_first ASC;
UPDATE district SET d_ytd = d_ytd + ":-:|'d_ytd','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','district'|:-:" WHERE (d_w_id = ":-:|'d_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','district'|:-:") AND (d_id = ":-:|'d_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','district'|:-:") RETURNING d_name, d_street_1, d_street_2, d_city, d_state, d_zip;
COMMIT;
-------End Transaction-------
-------Begin Transaction------
BEGIN;
UPDATE customer SET (c_balance, c_ytd_payment, c_payment_cnt, c_data) = (":-:|'c_balance','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','customer'|:-:", ":-:|'c_ytd_payment','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','customer'|:-:", ":-:|'c_payment_cnt','INT8','NOT NULL','','','','','','UPDATE','customer'|:-:", ":-:|'c_data','VARCHAR(500)','NOT NULL','','','','','','UPDATE','customer'|:-:") WHERE ((c_w_id = ":-:|'c_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:") AND (c_d_id = ":-:|'c_d_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:")) AND (c_id = ":-:|'c_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','customer'|:-:") RETURNING c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_since, c_credit, c_credit_lim, c_discount, c_balance, CASE c_credit WHEN ":-:|'c_credit','CHAR(2)','NOT NULL','','','','','','INSERT','customer'|:-:" THEN left(c_data, _) ELSE ":-:|'c_credit','CHAR(2)','NOT NULL','','','','','','INSERT','customer'|:-:" END;
INSERT INTO history(h_c_id, h_c_d_id, h_c_w_id, h_d_id, h_w_id, h_amount, h_date, h_data) VALUES (":-:|'h_c_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_c_d_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_c_w_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_d_id','INT8','NOT NULL','','','','','','INSERT','history'|:-:", ":-:|'h_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','INSERT','history'|:-:", ":-:|'h_amount','DECIMAL(6,2)','NULL','','','','','','INSERT','history'|:-:", ":-:|'h_date','TIMESTAMP','NULL','','','','','','INSERT','history'|:-:", ":-:|'h_data','VARCHAR(24)','NULL','','','','','','INSERT','history'|:-:");
UPDATE warehouse SET w_ytd = w_ytd + ":-:|'w_ytd','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','warehouse'|:-:" WHERE w_id = ":-:|'w_id','INT8','NOT NULL','PRIMARY KEY','','UNIQUE','','','WHERE','warehouse'|:-:" RETURNING w_name, w_street_1, w_street_2, w_city, w_state, w_zip;
UPDATE district SET d_ytd = d_ytd + ":-:|'d_ytd','DECIMAL(12,2)','NOT NULL','','','','','','UPDATE','district'|:-:" WHERE (d_w_id = ":-:|'d_w_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','district'|:-:") AND (d_id = ":-:|'d_id','INT8','NOT NULL','PRIMARY KEY','','','','','WHERE','district'|:-:") RETURNING d_name, d_street_1, d_street_2, d_city, d_state, d_zip;
COMMIT;
-------End Transaction-------
