# Yaml for creating and configuring the drt-chaos and workload-chaos clusters. This also configures the datadog.
environment:
  ROACHPROD_GCE_DEFAULT_SERVICE_ACCOUNT: 622274581499-compute@developer.gserviceaccount.com
  ROACHPROD_DNS: drt.crdb.io
  ROACHPROD_GCE_DNS_DOMAIN: drt.crdb.io
  ROACHPROD_GCE_DNS_ZONE: drt
  ROACHPROD_GCE_DEFAULT_PROJECT: cockroach-drt
  CLUSTER: drt-bhaskar
  CLUSTER_NODES: 3
  WORKLOAD_CLUSTER: workload-bhaskar
  WORKLOAD_NODES: 1
  COCKROACH_VERSION: v24.3.8

targets:
  - target_name: $CLUSTER
    steps:
      - script: ls
        args:
          - cockroach
