# Yaml to create a test-cluster. Please make sure that you change the cluster names to avoid conflicts.
environment:
  ROACHPROD_GCE_DEFAULT_SERVICE_ACCOUNT: 622274581499-compute@developer.gserviceaccount.com
  ROACHPROD_DNS: drt.crdb.io
  ROACHPROD_GCE_DNS_DOMAIN: drt.crdb.io
  ROACHPROD_GCE_DNS_ZONE: drt
  ROACHPROD_GCE_DEFAULT_PROJECT: cockroach-drt
  CLUSTER: drt-test
  WORKLOAD_CLUSTER: workload-test
  CLUSTER_NODES: 3
  WORKLOAD_NODES: 1

targets:
  # crdb cluster specs
  - target_name: $CLUSTER
    steps:
      - command: list
  # workload cluster specs
  - target_name: $WORKLOAD_CLUSTER
    steps:
      - command: status
        args:
          - drt-chaos
  - target_name: post_tasks
    dependent_targets:
      - $CLUSTER
      - $WORKLOAD_CLUSTER
    steps:
      - script: ls
      - script: cd
      - script: whoami
      - script: ps
        wait: -1
      - script: which drtprod
