# Yaml for creating and configuring the drt-chaos and workload-chaos clusters. This also configures the datadog.
environment:
  ROACHPROD_GCE_DEFAULT_SERVICE_ACCOUNT: 622274581499-compute@developer.gserviceaccount.com
  ROACHPROD_DNS: drt.crdb.io
  ROACHPROD_GCE_DNS_DOMAIN: drt.crdb.io
  ROACHPROD_GCE_DNS_ZONE: drt
  ROACHPROD_GCE_DEFAULT_PROJECT: cockroach-drt

  CLUSTER: drt-bhaskar
  CLUSTER_NODES: 3
  WORKLOAD_CLUSTER: workload-bhaskar
  WORKLOAD_NODES: 1
  COCKROACH_VERSION: v25.2.0

targets:
  - target_name: $CLUSTER
    steps:
      - command: create
        args:
          - $CLUSTER
        flags:
          clouds: gce
          gce-zones: "us-east1-d,us-east1-b,us-east1-c"
          nodes: $CLUSTER_NODES
          username: drt
        on_rollback:
          - command: destroy
            args:
              - $CLUSTER
      - command: sync
      - command: stage
        args:
          - $CLUSTER
          - release
          - $COCKROACH_VERSION
      - command: start
        args:
          - $CLUSTER
          - "--binary"
          - "./cockroach"
        flags:
          secure: true
          enable-fluent-sink: true
          restart: false
          sql-port: 26257
        on_rollback:
          - command: stop
            args:
              - $CLUSTER
      - command: run
        args:
          - $CLUSTER
          - --
          - "sudo systemctl unmask cron.service ; sudo systemctl enable cron.service ; echo \"crontab -l ; echo '@reboot sleep 100 && ~/cockroach.sh' | crontab -\" > t.sh ; sh t.sh ; rm t.sh"
  - target_name: $WORKLOAD_CLUSTER
    steps:
      - command: create
        args:
          - $WORKLOAD_CLUSTER
        flags:
          clouds: gce
          gce-zones: "us-east1-c"
          nodes: $WORKLOAD_NODES
          gce-machine-type: n2-standard-2
          os-volume-size: 100
          username: workload
          lifetime: 8760h
        on_rollback:
          - command: destroy
            args:
              - $WORKLOAD_CLUSTER
      - command: sync
        flags:
          clouds: gce
      - command: stage
        args:
          - $WORKLOAD_CLUSTER
          - cockroach
      - command: put
        args:
          - $WORKLOAD_CLUSTER
          - artifacts/drtprod
      - command: put
        args:
          - $WORKLOAD_CLUSTER
          - artifacts/roachtest
          - roachtest-operations
  - target_name: post_tasks
    dependent_targets:
      - $CLUSTER
      - $WORKLOAD_CLUSTER
    steps:
      - script: rm
        args:
          - -rf
          - certs-$CLUSTER
      - command: get
        args:
          - $CLUSTER:1
          - certs
          - certs-$CLUSTER
      - command: ssh
        args:
          - $WORKLOAD_CLUSTER
          - --
          - sudo
          - rm
          - -rf
          - certs
      - command: put
        args:
          - $WORKLOAD_CLUSTER
          - certs-$CLUSTER
          - certs
      - command: ssh
        args:
          - $WORKLOAD_CLUSTER
          - --
          - chmod
          - 600
          - './certs/*'
      - script: "pkg/cmd/drtprod/scripts/tpcc_init.sh"
        args:
          - cct_tpcc # suffix added to script name tpcc_init_cct_tpcc.sh
          - false # determines whether to execute the script immediately on workload node
        flags:
          warehouses: 200
          db: cct_tpcc
      - script: "pkg/cmd/drtprod/scripts/generate_tpcc_run.sh"
        args:
          - cct_tpcc # suffix added to script name tpcc_run.sh
          - false # determines whether to execute the script immediately on workload node
        flags:
          db: cct_tpcc
          warehouses: 200
          max-rate: 50
          workers: 5
          conns: 5
          duration: 12h
          ramp: 10m
          wait: 0
      - script: "pkg/cmd/drtprod/scripts/create_run_operation.sh"
        args:
          - "schema_change,add-column|add-index"
      - command: ssh
        args:
          - $WORKLOAD_CLUSTER
          - --
          - /home/ubuntu/tpcc_init_cct_tpcc.sh
      - command: ssh
        args:
          - $WORKLOAD_CLUSTER
          - --
          - sudo systemd-run --unit tpcc_run_cct_tpcc --same-dir --uid $(id -u) --gid $(id -g) bash /home/ubuntu/tpcc_run_cct_tpcc.sh
      - command: ssh
        args:
          - $WORKLOAD_CLUSTER
          - --
          - /home/ubuntu/run_ops_schema_change.sh
        wait_before: -1
